- name: create mount points
  ansible.builtin.file:
    path: "/mnt/{{ item }}"
    mode: 0775
    state: directory
    owner: "{{ ansible_user}}"
    group: "{{ ansible_user }}"
  loop: "{{ mountpoints }}"