#--- install docker, docker compose ---
- name: add docker gpg apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo to apt
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present 

- name: apt update
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    state: latest

- name: install docker prereq, docker community edition, and docker compose
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io  
      - docker-compose-plugin
    state: latest

- name: create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
    state: present