#REBOOT IF REQUIRED - see: https://aaronsaray.com/2021/ansible-reboot-if-required/
# update /etc/needrestart/needrestart.conf for auto-service restart
  #https://askubuntu.com/a/1421221
- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true