- name: Update docker containers
  shell:
    cmd: "docker compose pull && docker compose up -d --remove-orphans"
    chdir: "{{ docker_dir }}"
  register: docker_update_result

- name: Show update output
  debug:
    msg: "{{ docker_update_result.stdout_lines }}"

- name: Prune docker system
  shell:
    cmd: "docker system prune -f"
    chdir: "{{ docker_dir }}"
  register: docker_prune_result

- name: Show prune output
  debug:
    msg: "{{ docker_prune_result.stdout_lines }}"