- hosts: orangepihole
  become: yes
  vars:
    user: orangepi

  tasks:
#--- system update + upgrade ---
  - name: apt update + upgrade
    apt:
      state: latest
      upgrade: "full"
      update_cache: yes
      only_upgrade: yes
      autoclean: yes
      autoremove: yes
      cache_valid_time: 3600

#--- install docker ---
  - name: install required docker packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - software-properties-common
      state: latest
  
  - name: add docker gpg apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repo to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present 
  
  - name: install docker and docker-compose
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io  
        - docker-compose-plugin
      state: latest
  
  - name: create docker group
    group:
      name: docker
      state: present

  - name: add user to docker group
    user:
      name: "{{ user }}"
      groups: docker
      append: yes
      state: present